name: Build and Store

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Export Next.js application
        run: npm run export

      - name: Move exported files to 'build-output' directory
        run: |
          mkdir build-output
          mv out/* build-output/

      - name: Configure Git
        run: |
          git config --global user.email "ben@networkprovidersinc.com"
          git config --global user.name "benjaminNPI"

      - name: Commit changes
        run: |
          git add build-output
          git commit -m "Add exported static files"
          git pull origin main --rebase  # Fetch and rebase with main branch changes
          git push origin main
