name: Daily Build

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'  # Adjust to your Node.js version

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Install dependencies
        run: ${{ env.runner }} ${{ env.command }}

      - name: Build and Export with Next.js
        run: ${{ env.runner }} next build && ${{ env.runner }} next export

      - name: Prepare artifact
        run: mv out data-to-send.json  # Assuming you have data to send in JSON format

  # Deployment job (sends data to webhook)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send data to webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Define this secret in your repository settings
        run: |
          curl -X POST -H "Content-Type: application/json" -d @data-to-send.json $WEBHOOK_URL
