name: Build and Store

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install

      - name: Export with Next.js
        run: npm run export

      - name: Move build folder
        run: mv .next out

      - name: Commit changes
        run: |
          git config --global user.email "ben@networkprovidersinc.com"
          git config --global user.name "benjaminNPI"
          git add build-output
          git commit -m "Add built files"
          git push origin main
